from application import db
from application.models import Todos
db.drop_all()
db.create_all()

sample_todo= Todos(task = "Sample todo",completed = False)
sample_todo2= Todos(task = "Sample todo2",completed = True)
sample_todo3= Todos(task = "Sample todo3",completed = False)
sample_todo4= Todos(task = "Sample todo4",completed = True)
sample_todo5= Todos(task = "Sample todo5",completed = False)
db.session.add(sample_todo)
db.session.commit()
db.session.add(sample_todo2)
db.session.commit()
db.session.add(sample_todo3)
db.session.commit()
db.session.add(sample_todo4)
db.session.commit()
db.session.add(sample_todo5)
db.session.commit()